---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: secrets-manager
  name: secrets-manager
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-manager
  labels:
    app: secrets-manager
rules:
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "update"
  - "delete"
  - "create"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-manager
  namespace: default
  labels:
    app: secrets-manager
rules:
- apiGroups:
  - ""
  resources:
  - "configmaps"
  verbs:
  - "get"
  - "list"
  - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrets-manager
  labels:
    app: secrets-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secrets-manager
subjects:
  - kind: ServiceAccount
    name: secrets-manager
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-manager
  namespace: default
  labels:
    app: secrets-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-manager
subjects:
  - kind: ServiceAccount
    name: secrets-manager
    namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: secrets-manager-config
  namespace: default
data:
  secretDefinitions: |-
    - name: supersecret1
      type: kubernetes.io/tls
      namespaces:
      - default
      data:
        tls.crt:
          encoding: base64
          path: secret/data/pathtosecret1
          key: value
        tls.key:
          encoding: base64
          path: secret/data/pathtosecret3
          key: value

    - name: supersecret2
      type: Opaque
      namespaces:
      - default
      data:
        value1:
          path: secret/data/pathtosecret1
          key: value
        value2:
          path: secret/data/pathtosecret2
          key: value
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: secrets-manager
  name: secrets-manager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secrets-manager
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: secrets-manager
    spec:
      serviceAccountName: secrets-manager
      containers:
      - image: secrets-manager:v1.0.1
        imagePullPolicy: IfNotPresent
        name: secrets-manager
        args:
        - -vault.url=http://vault:8200
        - -log.level=debug
        env:
        - name: VAULT_ROLE_ID
          valueFrom:
            secretKeyRef:
              name: vault-approle-secret
              key: role_id
        - name: VAULT_SECRET_ID
          valueFrom:
            secretKeyRef:
              name: vault-approle-secret
              key: secret_id
      dnsPolicy: ClusterFirst
      restartPolicy: Always
